name: "Terraform"

permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  speculative-run:
    runs-on: ubuntu-latest
    name: TF CI/CD
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    permissions:
      pull-requests: write
    steps:

      - name: Retrieve latest state file
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        id: region
        with:
          command: 'iam region list --raw-output'
          query: "data[0].key"
          silent: false

      - name: Test1
        run: echo ${{ steps.region.outputs.raw_output }} 

      - name: Test2
        run: echo ${{ steps.region.outputs.output }} 
